/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CustomDialog: typeof import('./components/CustomDialog.vue')['default']
    CustomHeader: typeof import('./components/CustomHeader.vue')['default']
    DropButton: typeof import('./components/DropButton.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    MessageContainer: typeof import('./components/MessageContainer.vue')['default']
    MessageItem: typeof import('./components/messageItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SwitchButton: typeof import('./components/SwitchButton.vue')['default']
    TaskBar: typeof import('./components/taskBar.vue')['default']
    VideoContainer: typeof import('./components/VideoContainer.vue')['default']
    VideoItem: typeof import('./components/VideoItem.vue')['default']
  }
}
