name: deploy client to cloudflare pages
on:
  push:
    branches: ["main"]
    paths:
      - "liveKit-client/**"
      - ".github/workflows/deploy-client.yml"

env:
  NODE_VERSION: "18.x" # set this to the node version to use
  DIRECTORY: liveKit-client

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
       run:
         working-directory: ./${{ env.DIRECTORY }}/
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "yarn"

      - name: yarn install
        run: |
          npm install -D typescript
          yarn

      - name: yarn build
        run: |
          export NODE_ENV=production
          yarn build-only

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: ${{ env.DIRECTORY }}/dist

  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    needs: build
    name: Publish to Cloudflare Pages
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      # Run a build step here if your project requires

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 8037fd37fc7a665dfeee4347a23fc913
          projectName: livekit-client
          directory: .
          # Optional: Change the Wrangler version, allows you to point to a specific version or a tag such as `beta`
          wranglerVersion: "3"
